# Loading Data
Now that we are more familiar with the NumPy and Pandas packages, we can start loading data into Python to start working with. We can load data into our notebook a few different ways. Four different ways that we'll look at in this notebook are:
1. Generating data within our notebook using `np.arange()`
2. Generating data within our notebook using `np.random` functions
3. Importing external data into our notebook using Pandas DataReader
4. Importing an external .csv file into our notebook

## Generating Data with NumPy arange

In the last chapter, we demonstrated how to create numpy arrays by providing all the values in an array. Numpy also allows us to more efficiently generate a range of values. Let's first look at the `arange()` function that creates a range of intervals. The value 30 that we put inside the parentheses is the ending interval of the array. This means that Array_3 will start at 0, and end before 30.

In [1]:
import numpy as np
Array_3 = np.arange(30)
Array_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

We can also provide a starting interval, in this case 3, and an ending interval, in this case 7. This array starts at 3 and ends before 7.

In [11]:
np.arange(3,7)

array([3, 4, 5, 6])

Another information we can add is a step. For example, let's create an array starting at 1, ending at 10, and the 2 step means the range runs every other number. And again, it goes up to but not the last value.

In [15]:
# Arrange (starting interval, ending interval, step)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

The last two examples are arrays consists of a range of integers. We can also gather a range of float values within an interval. For this purpose we'll use the `linspace()` function. This function includes a starting value, an ending value, and the number of items in this array. This example will return 20 values evenly spaced between 0 to 5.

In [ ]:
# Gathering a range of values within an interval can also be done.
np.linspace(0,5,20)

In [23]:
# Gathering a range of values within an interval can also be done.
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

A range has similar properties as lists and other numpy arrays when it comes to indexing. Let's use Array_3 that we created earlier as an example. To call the 5th value within the array, we call index 4 in the square brackes.

In [33]:
Array_3[4]

4

## Generating Data with NumPy random

There are a lot of functions that allow us to generate randomized values in a numpy array. Let start with `random.rand` function. It generates random floats from 0 to 1. In the parentheses we can put how many numbers we want to generate. In this example we generated 10 random floats.

In [39]:
# creating an array of random floats
np.random.rand(10)

array([0.57603   , 0.53616622, 0.68813121, 0.40779964, 0.26871454,
       0.64432221, 0.34173949, 0.52524011, 0.87945939, 0.27084773])

Another function we can use is the `random.randint` function. It can be used to gather a random integer within a range. For example, we will have a random whole number between 10 and 20. It is important to note that this function includes 10 up to 19.

In [57]:
# gathering a random interger within a range
np.random.randint(10,20)

18

If we add a number in the end, we can generate a number of random integers wthin this range. This example creates an array of 5 integers in between 10 and 20. We might get repeatative values from the random functions.

In [65]:
# gathering an array of random intergers within a range
np.random.randint(10,20,5)

array([14, 13, 13, 17, 10])

We can also create a random matrix by providing a shape. For example, let's create an array of integers in between 1 and 100, the matrix contains 2 rows and 4 columns. 

In [79]:
np.random.randint(1,101,(2,4))

array([[58, 92, 60, 46],
       [84, 14, 73, 32]])

Since all the numbers are randomly generated, if we run all of these functions again we're likely to get completely different values. If we want to generate a random number and keep it throughout a model, we can use the seed function.

Seed function tells Python under the hood to "randomize" from the same method for any computer.  So, it basically eliminates randomness.  We would do this to ensure reproducibiliy.  But in production, randomization helps in forecasting, so you could disable seed there.

In [98]:
# fixing the randomizer to get the same random values for reproduction
np.random.seed(11)
np.random.rand(3)

array([0.18026969, 0.01947524, 0.46321853])

If we remove the seed line, we'll get 3 different values every time we run the code.

In [101]:
# without the seed
np.random.rand(3)

array([0.72493393, 0.4202036 , 0.4854271 ])

If we run the same code again, adding back the seed, we get the same result.

In [104]:
np.random.seed(11)
np.random.rand(3)

array([0.18026969, 0.01947524, 0.46321853])

In [ ]:
## Importing External Data with Pandas DataReader

Rather than defining our data manually, we can leverage functionality within Pandas to connect to and import external data into our notebook.

Functions from `pandas_datareader.data` extract external data from the web into a Pandas DataFrame. We'll look at an example of using datareader to import financial data from Naver.

In [118]:

!pip install pandas_datareader
# Import Packages
import pandas as pd
import pandas_datareader.data as pdr

# The first argument is the specific stock or index we want to retrive data for
# 005930 corresponds to Samsung on the KOSPI index

# The second argument is the data source we want to connect to - in our example it's naver

pdr.DataReader('005930','naver','2020-02-01','2025-02-01')

# We also need to define the start and end date for the days of information that we want to import into our DataFrame


Open   High    Low  Close    Volume
Date                                            
2020-02-03  55500  57400  55200  57200  23995260
2020-02-04  57100  59000  56800  58900  21800192
2020-02-05  60000  60200  58900  59500  19278165
2020-02-06  60100  61100  59700  61100  14727159
2020-02-07  61100  61200  59700  60400  16402493
...           ...    ...    ...    ...       ...
2025-01-21  53700  54300  53300  53500  13535702
2025-01-22  53400  54400  53100  54300  18341991
2025-01-23  53700  54100  53500  53700  15588067
2025-01-24  53600  53800  53200  53700  11867631
2025-01-31  52200  53000  51700  52400  42186279

[1229 rows x 5 columns]

We can use functions from the `yfinance` package to connect to yahoo finance data for a particular stock, in this case an ETF that tracks the S&P 500 stock market index. This time we can define our arguments outside of the function. This will make them easier to find and change in the future. We can also store the resulting DataFrame for future use in our notebook.

In [122]:
!pip install yfinance
# Import yfinance for yahoo data
import yfinance as yf
stock = 'SPY'
startdate = '2022-01-01'
enddate = '2025-01-31'

stocks_df = yf.download(stock, start=startdate,end=enddate)

print(stocks_df)

     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 3.0/3.0 MB 25.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.9-py3-none-any.whl size=139096 sha256=5611d5f9e4f6c1e195d45943e7221a44985774f82d01f8131e4ae7b9654d2677
  Stored in directory: c:\users\aswin\appdata\local\pip\cache\wheels\43\ef\2d\2c51d496bf084945ffdf838b4cc8767b8ba1cc20eb41588831
Successfully built peewee
YF.download() has changed argument auto_adjust default to True


[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date                                                                 
2022-01-03  457.181580  457.315577  453.487468  455.832167   72668200
2022-01-04  457.028473  459.354072  455.143128  458.626722   71178700
2022-01-05  448.252533  457.440003  448.156824  456.655233  104538900
2022-01-06  447.831421  450.587665  445.429273  447.783581   86858900
2022-01-07  446.060944  449.037314  444.682822  447.841030   85111600
...                ...         ...         ...         ...        ...
2025-01-24  607.969971  610.780029  606.799988  609.809998   34604700
2025-01-27  599.369995  599.690002  594.640015  594.809998   70361100
2025-01-28  604.520020  605.369995  597.250000  600.619995   44433300
2025-01-29  601.809998  604.130005  599.219971  603.719971   37177400
2025-01-30  605.039978  606.599976  600.719971  603.960022   39281300

[772 rows x 5 colum

## Importing External .csv

One of the more powerful ways of creating a DataFrame is to import a .csv file. This will save tremendous amount of time in recreating a data source in Python and allow Python to read the data in. We can use the `pd.read.csv()` function to do this.

When using this function, either the relative file path or the complete file path must be submitted between quotation marks. For a relative file path, if the csv. file is in the same working directory folder as the notebook, you can simply submit the file name with the csv. suffix. 

If the file is in another folder, then you must provide extra information of the path pandas should take to refer to the file (ie. 'datafolder/Data Source.csv').

In [130]:
#Importing an external .csv using a relative file path
dataframe_3=pd.read_csv('Data Source.csv')
dataframe_3

Store                Date  CategoryID ProductID        Q1         Q2  \
0         1   3/10/2019 0:00:00           1  11XXRP-P  24924.50   46039.49   
1         1    6/4/2019 0:00:00           2  12XXRP-Q  50605.27   44682.74   
2         1   1/16/2019 0:00:00           3    13XXRP  13740.12   10887.84   
3         1  10/18/2019 0:00:00           4    14XXRP  39954.04  d35351.21   
4         1   4/11/2019 0:00:00           5  15XXRP-A  32229.38   29620.81   
...     ...                 ...         ...       ...       ...        ...   
1882     40   3/24/2019 0:00:00          44  4044XXRP   3280.00    3556.22   
1883     40   3/24/2019 0:00:00          44  4044XXRP   3280.00    3556.22   
1884     40   3/24/2019 0:00:00          44  4044XXRP   3280.00    3556.22   
1885     40   9/30/2019 0:00:00          49  4049XXRP      0.00        NaN   
1886     40   6/14/2019 0:00:00          43  4093XXRP  31080.68   26600.39   

            Q3        Q4  
0     41595.55       NaN  
1     47928.89       NaN  
2     11523.47       NaN  
3     36826.95       NaN  
4     26468.27       NaN  
...        ...       ...  
1882   2965.33   3041.41  
1883   2965.33   3041.41  
1884   2965.33   3041.41  
1885       NaN    -23.99  
1886  23709.23  22879.37  

[1887 rows x 8 columns]

In [136]:
dataframe_3.head(10)

Store                Date  CategoryID ProductID        Q1         Q2  \
0      1   3/10/2019 0:00:00           1  11XXRP-P  24924.50   46039.49   
1      1    6/4/2019 0:00:00           2  12XXRP-Q  50605.27   44682.74   
2      1   1/16/2019 0:00:00           3    13XXRP  13740.12   10887.84   
3      1  10/18/2019 0:00:00           4    14XXRP  39954.04  d35351.21   
4      1   4/11/2019 0:00:00           5  15XXRP-A  32229.38   29620.81   
5      1   5/30/2019 0:00:00           6    16XXRP   5749.03    9135.87   
6      1   12/1/2019 0:00:00           7    17XXRP  21084.08   18310.31   
7      1   2/22/2019 0:00:00           8  18XXRP-C  40129.01   37334.83   
8      1   6/17/2019 0:00:00           9    19XXRP  16930.99   16562.49   
9      1    3/3/2019 0:00:00          10   110XXRP  30721.50   31494.77   

         Q3        Q4  
0  41595.55       NaN  
1  47928.89       NaN  
2  11523.47       NaN  
3  36826.95       NaN  
4  26468.27       NaN  
5   6060.26       NaN  
6  19985.20       NaN  
7  38717.60       NaN  
8  15880.85  15175.52  
9  29634.13  27921.96

We will continue to work with .csv data in Python in the next section of this chapter. However, much like what we see in a real-world setting, data is not always perfect. We can see that we have errors in our data, such as NaN values and duplicates.